---
1:
  owner: not
  price: "100"
  status: home
  sign:
    x: 350
    "y": 71
    z: 186
  door:
    x: 350
    "y": 70
    z: 185
  join:
    x: 349
    "y": 71
    z: 185
  quit:
    x: 352
    "y": 71
    z: 185
...
